name: Main workflow
on:
  ## This tries to avoid unessesary pushes to forked repo
  ## development branches. No sense in a dev building every
  ## time they push for a PR and no one should be working on
  ## common branches in their fork.
  push:
    branches:
      - master
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'feature/**'
  ## Any pull request. Yes the syntax looks weird
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v1
      ## This installs the correct node version
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      ## Restore cache
      - name: Restore npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: cache-${{ hashFiles('package-lock.json') }}
      ## Install using CI
      - name: Install Dependencies
        run: npm ci
        env:
          CI: true
      ## Build the app in prep for publishing
      - name: Build App
        run: npm run build
        env:
          CI: true
      ## Runs jest unit and cypress e2e testing and merges coverage reports
      - name: Run Tests 
        run: npm test
        env:
          CI: true
      